version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gitsubmodule
    directory: "/roles"
    schedule:
      interval: daily
