---
##
# Playbook to work around the pg8000 version limitation for Distributions that do not offer pg8000 >= 1.16 (See: https://docs.bareos.org/TasksAndConcepts/Plugins.html#prerequisites-for-the-postgresql-plugin)
# Installs the Python module pg8000 in a newer version via PIP to the Bareos library location in /usr/lib/bareos/plugins/ so it's used automatically.

- name: Installs Python pg8000 via PIP to /usr/lib/bareos/plugins
  hosts: filedaemons
  become: true
  gather_facts: false
  tasks:
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install Python pg8000 to Bareos Plugin library
      ansible.builtin.pip:
        name: pg8000
        extra_args: "--target /usr/lib/bareos/plugins/ --exists-action i -q"
