---

##
# Playbook to work around the pg8000 version limitation for Distributions that do not offer pg8000 >= 1.16 (See: https://docs.bareos.org/TasksAndConcepts/Plugins.html#prerequisites-for-the-postgresql-plugin)
# Installs the Python module pg8000 in a newer version via PIP to the Bareos library location in /usr/lib/bareos/plugins/ so it's used automatically.

- name: Installs Python pg8000 via PIP to /usr/lib/bareos/plugins
  hosts: filedaemons
  become: true
  gather_facts: false
  tasks:
    - name: Create dedicated directory in Bareos Plugin library
      ansible.builtin.file:
        name: /usr/lib/bareos/plugins/pg8000
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install Python pg8000 to Bareos Plugin library
      ansible.builtin.pip:
        name: pg8000
        extra_args: "--target /usr/lib/bareos/plugins/pg8000 --exists-action i -q"
      notify:
        - Restart Bareos FD

  handlers:
    - name: Restart Bareos FD
      ansible.builtin.service:
        name: bareos-filedaemon.service
        state: restarted
        daemon_reload: true
