---
name: Build and deploy Collection on Ansible Galaxy
on:
  release:
    types:
      - published
    tags:
      - 'v*'

jobs:
  deploy:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-collection.yaml@a833edc3ef3b044b24c8d1bc942d97b6f3a0609e # v0.11.0
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
