---
name: Build and deploy Collection on Ansible Galaxy
on:
  release:
    types:
      - published
    tags:
      - 'v*'

jobs:
  deploy:
    uses: adfinis/github-workflows-bareos/.github/workflows/ansible-collection.yaml@e5f6f4f45de85bb92d71713f9c539abf424528ac # v0.10.1
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
